name: Token Efficiency Monitoring

on:
  schedule:
    - cron: '0 0 * * *'  # Täglich um Mitternacht
  workflow_dispatch:  # Manuelle Auslösung möglich

jobs:
  analyze:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.9'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install tiktoken
    
    - name: Analyze Token Efficiency
      run: |
        python validation/token_efficiency.py .
    
    - name: Generate Efficiency Report
      run: |
        python validation/token_efficiency.py . --output token_efficiency_daily_report.json
    
    - name: Upload Daily Report
      uses: actions/upload-artifact@v3
      with:
        name: daily-token-efficiency-report
        path: token_efficiency_daily_report.json
    
    - name: Analyze Trends
      run: |
        # Platz für zusätzliche Trend-Analyse-Skripte
        echo "Analyzing token efficiency trends..."